name: hello-world

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: sync-environment-test
        uses: jpoehnelt/secrets-sync-action@v1.7.2
        with:
          SECRETS: |
            ^FOO
          REPOSITORIES: |
            suleimanwsa/helm-values
          DRY_RUN: false
          GITHUB_TOKEN: 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
          CONCURRENCY: 10
