name: hello-world

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: sync-environment-test
        uses: jpoehnelt/secrets-sync-action@v1.9.0
        with:
          SECRETS: |
            FOO
          REPOSITORIES: |
            suleimanwsa/helm-values
          GITHUB_TOKEN: ${{ secrets.READ_GITHUB_REPO_PAT }}
          CONCURRENCY: 10
          DRY_RUN: false
        env:
          FOO: ${{github.run_id}}
