name: hello-world

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: sync-environment-test
        uses: jpoehnelt/secrets-sync-action@v1.9.0
        with:
          environment: test
          SECRETS: |
            ^READ_GITHUB_REPO_PAT
          REPOSITORIES: |
            ^suleimanwsa/helm-values
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.READ_GITHUB_REPO_PAT }}
          CONCURRENCY: 10
        env:
          FOO: ${{github.run_id}}
