name: Replace Placeholders

on:
  push:
    branches:
      - main

jobs:
  replace_placeholders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace placeholders in file
        run: |
          sed -i 's/${string}/${{ secrets.string }}/g' ./test.properties
          cat ./test.properties

