name: subs

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Substitute Secrets Action
      uses: faradaytrs/substitute-secrets-action@v2.1.0
      with:
        substitutionRegex: \$\{([A-Z0-9_]+)\}
        input: '**/*.properties'
        substitutionData: ${{ toJSON(secrets) }}
        throwOnDataMissing: true
