name: Sync Repository Secrets and Variables

on:
  push:
    branches:
      - main

jobs:
  sync-repo-secrets-and-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Sync Secrets and Variables
        run: |
          variablet=$(cat test.properties)
          formatted_env=$(echo "${{ format('Environment: {0}', '$variablet') }}")
          echo $formatted_env
          formatted_secret=$(echo "${{ vars[format('{0}', 'FOO')] }}")
          echo $formatted_secret
           
