name: Sync Repository Secrets and Variables

on:
  push:
    branches:
      - main

jobs:
  sync-repo-secrets-and-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Secrets and Variables
        run: |
          variablet=$(cat test.properties)
          test={{ "$variablet" }}
          echo $test
           
