name: Sync Repository Secrets and Variables

on:
  push:
    branches:
      - main

jobs:
  sync-repo-secrets-and-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Check out domain repository
        uses: actions/checkout@v4
        # with:
        #   path: domain
      - name: Check out central repository
        uses: actions/checkout@v4
        with:
          repository: suleimanwsa/charts
          # token: ${{secrets.READ_GITHUB_REPO_PAT}}
          # ref: feature/DDM-588-connectors-gha
          # path: dande-centraldomain
      - name: Replace placeholders in file
        run: |
          ls -lrt
           
