name: Sync Repository Secrets and Variables

on:
  push:
    branches:
      - main

jobs:
  sync-repo-secrets-and-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Check out domain repository
        uses: actions/checkout@v4
        with:
          path: .
      - name: Check out central repository
        uses: actions/checkout@v4
        with:
          repository: suleimanwsa/charts
          path: .
      - name: Replace placeholders in file
        run: |
          ls -lrt
          echo ${{ github.repository }}
           
